### ISSUE TITLE
issue in navbar login/sign-up button padding

### ISSUE THREAD

**Issue by Sohardbegraj** [dubinc/dub#2526]
![Image](https://github.com/user-attachments/assets/ddc0f67e-18d0-4002-b8f0-62e58595654e)

**Comment by asharan2511** [comment]
I see the Issue is already fixed. Is there something im missing ? 

![Image](https://github.com/user-attachments/assets/1e98056a-685c-4f56-85cd-440b150b3a04)

**Comment by SnehaReddy10** [comment]
<img width="949" alt="Image" src="https://github.com/user-attachments/assets/c99b6b21-045f-41b6-b1be-c07dee60b492" />


I can still see the issue. Can I fix this?

**Comment by Devesh-x** [comment]
Hi! I'd like to work on this issue. Please assign it to me 😊

**Comment by devkiran** [comment]
@Sohardbegraj are you still seeing the issue? If so, feel free to reopen the issue.
